### ISSUE TITLE
Notify by email all customers that have articles in reserve.

### ISSUE THREAD

**Issue by miguelcalderons** [miw-upm/betca-tpv-spring#120]
Notify by maill all customers that have articles in reserve.

Estimated time: 2 hours.
Real time:

**Comment by miw-upm** [comment]
Estas comentando mal los commits. Debes añadir en el mensaje tu número de issue #xx

**Comment by miw-upm** [comment]
El merge 31/03/2019 19:42 8467124 es incorrecto. Debes primero actulizar los cambios de develop en tu issue. Me gustaría no tener que volverte a comentar este fallo

**Comment by miw-upm** [comment]
Además has dejado roto la rama develop!!!
