### ISSUE TITLE
closeOrder

### ISSUE THREAD

**Issue by miguelcalderons** [miw-upm/betca-tpv-spring#122]
closeOrderbyId that add the closed date and receive the finalAmount.

Estimated time: 2 hours.
Real time: 4 hours.

**Comment by miw-upm** [comment]
El commit 27/03/2019 0:23 es erroneo. No se debe fusionar un origin/develo con issue

**Comment by miw-upm** [comment]
El commit 30/03/2019 18:00 es erroneo. Se vuelve a cometer el mismo error que antes...
