### ISSUE TITLE
StockPrediction - Random Tickets generator

### ISSUE THREAD

**Issue by robertome** [miw-upm/betca-tpv-spring#21]
Querys para la recupera la información necesaria agrupandola según los datos de entrada (Semana, Mes, Año)

>Estimación: 3H

**Comment by robertome** [comment]
> Tiempo real: 6H

**Comment by miw-upm** [comment]
Tienes montado un lío con las ramas. Procura organizarte mejor. Asocias #21 con issue#22... 27/03/2019 1:08

**Comment by miw-upm** [comment]
El merge 27/03/2019 1:11 es incorrecto. En estos momentos del desarrollo del proyecto, se consideran errores importantes

**Comment by miw-upm** [comment]
Este issue esta cerrado pero esta en una rama muerta... 27/03/2019 1:15 ???

**Comment by robertome** [comment]
> 
> 
> Tienes montado un lío con las ramas. Procura organizarte mejor. Asocias #21 con issue#22... 27/03/2019 1:08

Buenas @miw-upm, #21 no esta asociado con issue#22, en ese momento subí develop después de realizar el merge de #21 en develop, y luego abrí el issue#22 a partir del develop y lo subi a remoto origin/issue#21.

> 
> 
> El merge 27/03/2019 1:11 es incorrecto. En estos momentos del desarrollo del proyecto, se consideran errores importantes
> Este issue esta cerrado pero esta en una rama muerta... 27/03/2019 1:15 ???
Buenas @miw-upm,  el merge 27/03/2019 1:11 es de la rama origin/issue#21 sobre mi local issue#21. 
Después de haber realizado el merge de issue#21 en develop y subir develop a remoto sin ningún problema, al intentar subir la rama issue#21 a remoto, me lanzó un mensaje de "rejected" y me pedía realizar un pull de la rama remota origin/issue#21 sobre mi local issue#21 para poder subirlo (no entiendo porque ya que no había cambios). La rama issue#21 aparece como una rama muerta porque no vi necesario volver a realizar el merge de la issue#21 en develop cuando no había cambiado nada, pero si te parece más correcto realizo otra vez el merge de la issue#21 sobre develop para que no quede como muerta.

Saludos
