### ISSUE TITLE
StockPrediction - Algoritmo de pronóstico

### ISSUE THREAD

**Issue by robertome** [miw-upm/betca-tpv-spring#22]
Implementación del método de cálculo para el pronóstico de stock 

> Estimación: 5H

**Comment by robertome** [comment]
>Tiempo real: 8

**Comment by miw-upm** [comment]
Has visto la evolución de las ramas entre 15:02 y 17:51 del 31/03/2019!!!
Una vez que realizas un issue en la rama, y tienes tu código sin errores, lo primero es realizar un fetch --all, y si tu develop local esta desactualizado con develop/origin, actualizar el develop local, y despues incorporar los cambios a tu rama...
Y lugo tienes un lio de fusiones... 60e3147 y  c161f94
