### ISSUE TITLE
Admins

### ISSUE THREAD

**Issue by socrtx** [miw-upm/betca-tpv-spring#26]
[Admins](https://github.com/miw-upm/betca-tpv-spring/wiki/Ampliaciones-curso-2017_18#admins)

**Comment by borja94** [comment]
Hola Carlos.
He visto que Travis se ha roto en el test con el nombre testPutCustomer, Travis dice que he sido yo pero estoy viendo que justo hemos hecho merge los dos de seguido y el error lo ha provocado tu commit. No quiero tocarlo, pues no se exactamente que es lo que estas haciendo.
Un saludo.
Pongo en copia a  @jesusBernalBermudez .

**Comment by socrtx** [comment]
Hola Borja!
No subí nada erróneo. 
Pongo en copia a @jesusBernalBermudez .
