### ISSUE TITLE
Statistics - Create Data Transfer Object

### ISSUE THREAD

**Issue by tomas-teston** [miw-upm/betca-tpv-spring#41]
> Estimated Time: 1h

**Comment by tomas-teston** [comment]
Time: 1h

**Comment by miw-upm** [comment]
Debes añadir #xx en todos los commits

**Comment by tomas-teston** [comment]
Metí el espacio mal entre el nombre de la issue y el número. Tendré más cuidado la próxima vez, disculpa. Un saludo.
